name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Set up Rust and build with Cargo
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build with Cargo
        run: cargo build

      # Step 2: Set up Haskell and build with Cabal
      - name: Set up Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.2.5'  
          cabal-version: '3.6.2.0'

      - name: Build with Cabal
        run: cabal build

      # Step 3: Run Cargo tests
      - name: Run Cargo tests
        run: cargo test
